name: budget_maker_app
description: A budget making app
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Package pour formatter les dates
  # https://pub.dev/packages/intl
  intl: any

  # Package pour la navigation
  # https://pub.dev/packages/beamer
  beamer: ^1.5.6

  # Package pour la gestopm de Firebase
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.15.0

  # Package pour la gestion de la base de données
  # https://pub.dev/packages/firebase_database
  firebase_database: ^10.2.4

  # Package pour la gestion de l'authentification
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^4.7.2

  # Package pour la connexion avec Google
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^6.1.4

  # Package pour valider les emails
  # https://pub.dev/packages/email_validator
  email_validator: ^2.1.17

  # Package pour l'affichage des carousels
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1

  # Package pour la gestion des évènements entre les widgets
  # https://pub.dev/packages/eventify
  eventify: ^1.0.1

  # Package pour la gestion du stockage local
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.0

  # Package pour la ligne de boutons animés (sélection du thème)
  # https://pub.dev/packages/animated_button_bar
  animated_button_bar: ^1.0.0

  # Package qui facilite la gestion des structures en dart
  # Donne entres autres beaucoup de fonctions utiles pour les listes
  # https://pub.dev/packages/collection
  collection: ^1.17.1

  # Package pour la gestion des images svg (logo)
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.7

  # Package pour la gestion des images (image de profil) en cache
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Package pour la génération des icônes de l'application
  flutter_launcher_icons: "^0.9.2"

  # Package pour la gestion de la qualité du code
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.2
  test: ^1.24.1

# Configuration pour la génération des icônes de l'application
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo-light.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
