// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXU-feiGUipVGfrlBHebWDBbnPIPxRJnc',
    appId: '1:143845314582:web:0f441ddf61df8b40352537',
    messagingSenderId: '143845314582',
    projectId: 'budget-maker-f62b3',
    authDomain: 'budget-maker-f62b3.firebaseapp.com',
    databaseURL: 'https://budget-maker-f62b3-default-rtdb.firebaseio.com',
    storageBucket: 'budget-maker-f62b3.appspot.com',
    measurementId: 'G-V0DVCPNFD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCita7huuw8_ayh7m8YLXMkOq1BtTpKONs',
    appId: '1:143845314582:android:92f034ac3dcdaf2d352537',
    messagingSenderId: '143845314582',
    projectId: 'budget-maker-f62b3',
    databaseURL: 'https://budget-maker-f62b3-default-rtdb.firebaseio.com',
    storageBucket: 'budget-maker-f62b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGER8sZ_-PoX080xQ2H5-p0xOtbhCf3iw',
    appId: '1:143845314582:ios:8f0e31731df966df352537',
    messagingSenderId: '143845314582',
    projectId: 'budget-maker-f62b3',
    databaseURL: 'https://budget-maker-f62b3-default-rtdb.firebaseio.com',
    storageBucket: 'budget-maker-f62b3.appspot.com',
    iosClientId: '143845314582-l1v6uq1gkcn8v5hqf4envj3r7ome480p.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetMakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGER8sZ_-PoX080xQ2H5-p0xOtbhCf3iw',
    appId: '1:143845314582:ios:8f0e31731df966df352537',
    messagingSenderId: '143845314582',
    projectId: 'budget-maker-f62b3',
    databaseURL: 'https://budget-maker-f62b3-default-rtdb.firebaseio.com',
    storageBucket: 'budget-maker-f62b3.appspot.com',
    iosClientId: '143845314582-l1v6uq1gkcn8v5hqf4envj3r7ome480p.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetMakerApp',
  );
}
